$globals:
  user: '{{ $env.USER }}'
  root: build
  dir: Hello
$files:
  example:
    from: config/example.stub
    to: "{{ $globals.root }}/{{ $globals.dir }}/Example.php"
  request:
    vars:
      foo: some
      user: '{{ $env.USER }}'
    from: |
      <?php

      namespace {{ namespace }};

      use Illuminate\Foundation\Http\FormRequest;

      class {{ class }} extends FormRequest
      {
          /**
          * Determine if the user is authorized to make this request.
          * @author {{ user }}
          */
          public function authorize(): bool
          {
              return true;
          }

          /**
          * Get the validation rules that apply to the request.
          *
          * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
          */
          public function rules(): array
          {
              return [
                  //
              ];
          }
      }
    to: "{{ $globals.root }}/app/Http/Requests/{{ $globals.dir }}/UpdateRequest.php"
    methods:
      - |
        /**
        * Get the dto from the request
        *
        * @return {{ $files.dto }}
        */
        public function toDto(): {{ $files.dto }}
        {
            return new {{ $files.dto }};
        }

  dto:
    from: |
      <?php

      namespace {{ namespace }};

      class {{ class }}
      {
          public function toArray(): array
          {
              return [
                  //
              ];
          }
      }

    to: "{{ $globals.root }}/app/Http/DTOs/{{ $globals.dir }}/UpdateDto.php"

  dto_test:
    skip: true
    from: |
      <?php

      namespace {{ namespace }};

      use Illuminate\Foundation\Testing\RefreshDatabase;
      use Illuminate\Foundation\Testing\WithFaker;
      use Tests\TestCase;

      class {{ class }} extends TestCase
      {
      }
    to: "{{ $globals.root }}/tests/Http/DTOs/{{ $globals.dir }}/UpdateDtoTest.php"
    methods:
      - |
        public function testToArray(): void
        {
            $dto = new {{ $files.dto }};
        }


  controller:
    from: |
      <?php

      namespace {{ namespace }};

      use App\Http\Controllers\Controller;
      use Illuminate\Http\Request;

      class {{ class }} extends Controller
      {
          //
      }

    to: "{{ $globals.root }}/app/Http/Controllers/{{ $globals.dir }}/MainController.php"
    methods:
      - |
        /**
        * ....
        * @param {{ $files.request }} $request
        */
        public function update({{ $files.request }} $request)
        {
            $dto = $request->toDto();
            {{ $files.model }}::updateByDto($dto);
        }
  controller_test:
    from: |
      <?php

      namespace {{ namespace }};

      use Illuminate\Foundation\Testing\RefreshDatabase;
      use Illuminate\Foundation\Testing\WithFaker;
      use Tests\TestCase;

      class {{ class }} extends TestCase
      {
      }
    to: "{{ $globals.root }}/tests/Http/Controllers/{{ $globals.dir }}/MainControllerTest.php"
    methods:
      - |
        public function testUpdate(): void
        {
            $response = $this->get('/');

            $response->assertStatus(200);
        }

  model:
    from: |
      <?php

      namespace {{ namespace }};

      use Illuminate\Database\Eloquent\Factories\HasFactory;
      use Illuminate\Database\Eloquent\Model;

      class {{ class }} extends Model
      {
          use HasFactory;
      }

    to: "{{ $globals.root }}/app/Models/{{ $globals.dir }}/Hello.php"
    methods:
      - |
        /**
        * ....
        *
        * @param {{ $files.dto }} $dto
        */
        public static function updateByDto({{ $files.dto }} $dto)
        {
            $data = $dto->toArray();
        }

  model_test:
    from: |
      <?php

      namespace {{ namespace }};

      use Illuminate\Foundation\Testing\RefreshDatabase;
      use Illuminate\Foundation\Testing\WithFaker;
      use Tests\TestCase;

      class {{ class }} extends TestCase
      {
      }
    to: "{{ $globals.root }}/tests/Models/{{ $globals.dir }}/HelloTest.php"
    methods:
      - |
        public function testUpdate(): void
        {
            $dto = new {{ $files.dto }};

            $model = {{ $files.model }}::updateByDto($dto);
        }
