files:
  request:
    from: config/request.stub
    to: app/Http/Requests/Hello/UpdateRequest.php
    methods:
      - |
        public function toDto(): {{ files.dto }}
        {
            return new {{ files.dto }};
        }

  dto:
    from: |
      <?php

      namespace {{ namespace }};

      class {{ class }}
      {
          public function toArray(): array
          {
              return [
              ];
          }
      }
    to: app/Http/DTOs/Hello/UpdateDto.php

  controller:
    placeholders:
      rootNamespace: App\
    from: |
      <?php

      namespace {{ namespace }};

      class {{ class }}
      {
          //
      }

    to: app/Http/Controllers/Hello/HelloController.php
    methods:
      - |
        public function update({{ files.request }} $request)
        {
        }
  model:
    from: |
      <?php

      namespace {{ namespace }};

      class {{ class }}
      {
          use HasFactory;
      }
    to: app/Models/Hello.php
    methods:
      - |
        public function static updateByName(string $name, string $value)
        {
        }
