name: build

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: zip, curl, xdebug
          coverage: xdebug

      - name: Update composer
        run: composer selfupdate

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run static analysis
        run: composer static-analysis
