name: Run lint

on:
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - "composer.json"
      - ".github/workflows/lint.yaml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} |egrep '\.php$' > .list.txt || true
          [ -s ./.list.txt ] && phpcs --standard=./phpcs.xml --file-list=./.list.txt
      - name: Update composer
        run: composer selfupdate

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run static analysis
        run: composer static-analysis